#+TITLE: Another C++ Linear Algerba library

* What is it?

This library is an *crazy* attempt to create another C++ Linear Algebra library. 

Compared to already existing libs like: [[http://eigen.tuxfamily.org/index.php?title=Main_Page][Eigen]], [[https://bitbucket.org/blaze-lib/blaze/src/master/][Blaze]], ...

The expected goal is a reasonable compilation time and with a concise
implementation wrapping libraries like Blas, Lapacke, etc. I want a
minimal number of lines of code!

In peculiar, for the moment I will not immediately implement
 Expression Templates, but simply provide call sites like:

#+begin_src cpp :eval never
expr(M, _assign_, 1, A, _transpose_, B, _plus_, 3, _matrix_0_);
#+end_src

which means: M = 1.A.B^t+3.M, where M, A and B are matrices.

*Reasons:* expression templates
- increase compilation time
- can always "hide" some temporary creation

** Disclaimer

 The library is at its early, early, early... development stage. I
 have made it public only for the curious...


* Examples

** Matrix types 

#+BEGIN_SRC sh :wrap "src cpp :eval never" :results output :exports results
cat $(pwd)/examples/some_matrix_types.cpp
#+END_SRC

#+RESULTS:
#+begin_src cpp :eval never
#include "LinearAlgebra/dense/matrix.hpp"
#include "LinearAlgebra/dense/vector.hpp"

#include <iostream>

using namespace LinearAlgebra;

int
main()
{
  Matrix<double> M_1(4, 5);

  Symmetric_Matrix<int> M_2(4, 4);

  Tiny_Lower_Triangular_Strict_Matrix<float, 4, 7> M_3;

  std::cout << M_1 << std::endl;
  std::cout << M_2 << std::endl;
  std::cout << M_3 << std::endl;
}
#+end_src

prints

#+BEGIN_SRC sh :wrap "example :eval never" :results output :exports results
./build/examples/some_matrix_types
#+END_SRC

#+RESULTS:
#+begin_example :eval never

               0               0               0               0               0
               0               0               0               0               0
               0               0               0               0               0
               0               0               0               0               0

               0               X               X               X
               0               0               X               X
               0               0               0               X
               0               0               0               0

               X               X               X               X               X               X               X
               0               X               X               X               X               X               X
               0               0               X               X               X               X               X
               0               0               0               X               X               X               X
#+end_example

** Expression usage example

Again this is not expression template, but IMHO this is still readable
and you do not have hidden temporary (plsu shorter compilation time).

#+BEGIN_SRC sh :wrap "src cpp :eval never" :results output :exports results
cat $(pwd)/examples/expr_usage.cpp
#+END_SRC

#+RESULTS:
#+begin_src cpp :eval never
#include "LinearAlgebra/vector.hpp"

#include <ccomplex>
#include <iostream>

using namespace LinearAlgebra;

int
main()
{
  using T = std::complex<double>;

  Vector<T> V_1(5), V_2(5);

  std::cout << V_1 << std::endl;

  expr(V_2, _assign_, V_1);

  std::cout << V_2 << std::endl;
}
#+end_src

prints

#+BEGIN_SRC sh :wrap "example :eval never" :results output :exports results
./build/examples/expr_usage
#+END_SRC

#+RESULTS:
#+begin_example :eval never

(0,0)
(0,0)
(0,0)
(0,0)
(0,0)

(0,0)
(0,0)
(0,0)
(0,0)
(0,0)
#+end_example

* API Documentation

** Available matrix types

For the moment only dense BLAS compatibles (column major) matrices are
defined (I expect to add sparse & triangular matrices too).

The generic definition for these matrix types is:
#+begin_src cpp :eval never
template <typename T, Matrix_Special_Structure_Enum SPECIAL_STRUCTURE,
          Matrix_Storage_Mask_Enum MASK, typename N_TYPE, typename M_TYPE,
          typename LEADING_DIMENSION>
class Default_Matrix { /* ... */ };
#+end_src

where 

| T                             | is the =element_type, can be a float, int or any user type                    |
| Matrix_Special_Structure_Enum | is in {None,Symmetric,Hermitian,Triangular,Unit_Triangular,Triangular_Strict} |
|                               |                                                                               |

