* M
  - Matrix
    - [[file:src/LinearAlgebra/dense/README.org::*=LinearAlgebra/dense/matrix_storage_scheme.hpp=][are_compatibles()]]
    - [[file:src/LinearAlgebra/dense/README.org::*tpoto][Matrix_Special_Structure_Enum]]
    - [[file:src/LinearAlgebra/dense/README.org::*tpoto][Matrix_Special_Structure_Imposes_Square_Matrix]]
* V
  - Vector
    - [[id:37ca8895-814e-4808-882f-fff1bde88bcc][Vector_Hierarchy]]
    - [[file:src/LinearAlgebra/dense/README.org::*Matrix classes][Vector_Hierarchy]]
