#+SETUPFILE: Setup/setupFile.org
#+TITLE: TODO list
* 2020
** 2020-03 March
*** 2020-03-11 Wednesday
*** 2020-03-15 Sunday

*** 2020-03-17 Tuesday

*** 2020-03-18 Wednesday

**** TODO Bug to fix! [0/2]                                          :Urgent:
     :PROPERTIES:
     :Created:  [2020-03-18 Wed 12:23]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/src/LinearAlgebra/expr_of_the_poor/V0_assign_alpha_V0_plus_beta_op_M_V1.hpp::assert(0);%20//return%20expr(v_0,%20_assign_,%20alpha,%20op,%20M,%20v_1,%20_plus_,%20beta,%20_vector_0_);]]

   #+BEGIN_QUOTE
      assert(0);

       //return expr(v_0, _assign_, alpha, op, M, v_1, _plus_, beta, _vector_0_);

   #+END_QUOTE

    - [ ] to fix

   Back link: [[file:~/GitHub/LinearAlgebra/test/expr_of_the_poor/known_patterns_impl.cpp:://%20does%20not%20compile%20ANYMORE%20//%20something%20has%20changed....%20TO%20FIX]]

   #+BEGIN_QUOTE
      does not compile ANYMORE
      something has changed.... TO FIX
   #+END_QUOTE

    - [ ] To fix


*** 2020-03-19 Thursday

**** DONE Remove inplace_map [1/1]                                 :Critical:
     :PROPERTIES:
     :Created:  [2020-03-19 Thu 12:56]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/src/LinearAlgebra/dense/vector_map.hpp::inplace_map]]

   #+BEGIN_QUOTE
    inplace_map
   #+END_QUOTE

    - [X] as ambiguous with transform. Use transform_indexed to do the job

*** 2020-03-21 Saturday


*** 2020-03-22 Sunday

*** 2020-03-23 Monday

**** TODO M=m to fix [0/0]                                         :Critical:
     :PROPERTIES:
     :Created:  [2020-03-23 Mon 12:17]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/test/LinearAlgebra/dense/matrix_view.cpp::expr(M,%20_assign_,%20m);]]

   #+BEGIN_QUOTE
     expr(M, _assign_, m);

   #+END_QUOTE
*** 2020-03-27 Friday

*** 2020-03-28 Saturday

**** TODO Document deep copy semantic of views [0/0]                    :Doc:
     :PROPERTIES:
     :Created:  [2020-03-28 Sat 11:49]
     :END:

   Back link: [[file:test/LinearAlgebra/expr/V_assign_V.cpp::Note:%20fundamental%20to%20understand%20to%20properly%20use%20this%20library!][operator= overloading meaning]]

   #+BEGIN_QUOTE
   Note: fundamental to understand to properly use this library!
   #+END_QUOTE

    - This part is *fundamental*.

**** TODO refactoring M_assign_alpha_M [0/0]                       :Critical:
     :PROPERTIES:
     :Created:  [2020-03-28 Sat 12:43]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/src/LinearAlgebra/expr/V_assign_alpha_V.hpp:://%20Define:%20V%20=%20%CE%B1%20V]]

   #+BEGIN_QUOTE

   #+END_QUOTE
*** 2020-03-30 Monday

**** TODO X0_assign_X1.hpp [0/0]                                   :Critical:
     :PROPERTIES:
     :Created:  [2020-03-30 Mon 13:25]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/src/LinearAlgebra/expr/X0_assign_X1.hpp][file:~/GitHub/LinearAlgebra/src/LinearAlgebra/expr/X0_assign_X1.hpp]]

    - A FINIR!!!!
*** 2020-03-31 Tuesday

**** TODO V0_assign_alpha_op_M_V1_plus_beta_V2_driver.hpp [0/0]    :Critical:
     :PROPERTIES:
     :Created:  [2020-03-31 Tue 16:59]
     :END:

   Back link: [[file:~/GitHub/LinearAlgebra/src/LinearAlgebra/expr/V0_assign_alpha_op_M_V1_plus_beta_V2_driver.hpp:://%20CAVEAT:%20TO%20RESTORE!%20here%20only%20to%20check%20expressions%20//%20static_assert(not%20std::is_same_v<M_TYPE,%20M_TYPE>,%20"Not%20implemented");%20//%20assert(0);]]

   #+BEGIN_QUOTE
       // CAVEAT: TO RESTORE! here only to check expressions
       //    static_assert(not std::is_same_v<M_TYPE, M_TYPE>, "Not implemented");
       //    assert(0);

   #+END_QUOTE

    - Restore once completed

